export const environment = {
  production: true,
  ssoServiceUrl: "https://qcan.adamsbridgestage.com/ssoService",
  // mongo_AuthServiceURL: "https://qcan.adamsbridgestage.com/crmauthService",
  mongo_AuthServiceURL: 'https://qcloginapi.adamsbridgestage.com/authService',
  mongo_FormServiceURL: "https://qcan.adamsbridgestage.com/formService",
  mongo_RealServServiceURL: "https://qcan.adamsbridgestage.com/realServService",
  report_builder_apiUrl: "https://qcan.adamsbridgestage.com/reportBuilderService",
  CRM_ApiUrl: "https://qcan.adamsbridgestage.com/CRMService",
  CRM_Transition_ApiUrl: "http://localhost:5010/CRMTransitionService",
  assetPath: "./",
  Companyid: "1",
  layoutSetting: {
    createnew: false,
    settings: true,
    role: true,
    company:true
  },
  themeSetting: {
    abg: true,
    lil: true,
    ims: true,
    cms: true,
    abgLight: true,
  },
  body: { UserName: "ticket", Password: "ao" + "sta", LogOpt: "1" },
  Ticket_Image: "https://ticketstage.adamsbridge.com",
  jsonUrl: "./assets/static-messages/static_eng_message.json",
  cryptoKey: "ao" + "sta" + "$123",
  enableSSO: false,
  reportServiceCollectionId: "2",
title:'CRM',
  recaptchaV3SiteKey: "6LffVJYqAAAAAK4N_I1lNFClv8027f0w4cNQ32s-",
  recaptchaV2SiteKey: "6LcdcpgqAAAAADyhuuxCJhBhVjDsoFvvqjpZX7qq",
  recaptchaV2URL: "https://www.google.com/recaptcha/api.js",

  gtagURL: "https://www.googletagmanager.com/gtag/js?id=G-7JP225NDE4",
  gtagKey: "G-7JP225NDE4",
  recaptchaSiteKeyWithURL: "https://www.google.com/recaptcha/enterprise.js?render=6LffVJYqAAAAAK4N_I1lNFClv8027f0w4cNQ32s-",
  scriptFile: `script[src^="https://www.google.com/recaptcha/enterprise.js"]`,

  SharedFilePath: "https://adamsbridgenet.sharepoint.com",
  SharePointAppName: "DevABGPortal",
  SHAREPOINT_CLIENT_ID: "2c70b035-8486-40f5-ab3b-c8523aecc76c@cf7323e2-013d-40b8-82a5-53db19b19fac",
  SHAREPOINT_SECRET: "2O5mj" + "FuMOcC" + "9oOEFS" + "0osqgU" + "7AaJG9" + "nqTexOo" + "vnUhxqg=",
  SHAREPOINT_RESOURCE: "00000003-0000-0ff1-ce00-000000000000/adamsbridgenet.sharepoint.com@cf7323e2-013d-40b8-82a5-53db19b19fac",
  SHAREPOINT_RESTCLIENT: "https://accounts.accesscontrol.windows.net/cf7323e2-013d-40b8-82a5-53db19b19fac/tokens/OAuth/2/",
  DOCUBEE_API_KEY: "ba7d1" + "3db-d1c7" + "-457d-8af0" + "-a995277" + "d43ac",
  DOCUBEE_API_URL: "https://app.ontask.io/api/v2/signatures",
  DOCUBEE_API_UPLOAD_URI: "https://app.ontask.io/api/v2/documents",
  DOCUBEE_API_SETFIELDS_URI: "https://docubee.app/api/v2/documents/",
  DOCUBEE_API_GET_SIGN_STATUS: "https://docubee.app/api/v2/signatures/",
  projectName: "crm",
  ACCESS_KEY: "abg_fs_vB" + "abgohfGf" + "GnJfg3wW" + "hpXghR9Z" + "FoDr4JmJ" + "I10ZxuCv" + "E24fn2ku" + "f2UlRcUK" + "ks1FwLz8" + "mvt0BTTW" + "Z5OtF5NO" + "GqrPgIpc" + "eIZ27w7e" + "QQ9BqTKA" + "Qu9b52zR" + "sYQEAsb",
  ipAddressUrl: "https://ipapi.co/json/?key=" + "fnqdj6" + "xwio1A" + "vjrfHA" + "QHT59k" + "XLNIt9" + "U9BqOz" + "rGJsEn" + "Bisgtv" + "HR",
  AdminAccess: '67d92e105425c6d074a24df0',
  socketUrl: "https://qcloginapi.adamsbridgestage.com",
  mongo_AuthServiceURL_commonAuth: 'https://qcloginapi.adamsbridgestage.com/authService',
  mongo_common_AuthServiceURL: "https://qcan.adamsbridgestage.com/authService",
  standAloneApp: false,
  crmProductsUrl: `https://qcan.adamsbridgestage.com/CRMService`,
  status_prospect : "6814e94099821ce96083f4ba",
  status_contracting : "668e1cd727e37e370e24d16d",
  status_active : "669e368f5e9bd054cee4151b",
  status_inactive : "668e1c7e27e37e370e24d165",
  status_DocumentEnd:"682c18912435c51e80d832d4",
  status_transition : "6819988cbc8dd11ae359a7cb",
  ticketingArticleUrl: `https://qcan.adamsbridgestage.com/ticketingService`,
  ticketkingAppUrl: `https://qcan.adamsbridgestage.com/tickets/#`,
  crm_socket: "https://qcan.adamsbridgestage.com",
  crm_transition_socket: "https://qcan.adamsbridgestage.com",
  audit_logUrl: "https://qcan.adamsbridgestage.com/CRMService/fileTransaction",
  fileStorageApiUrl: "https://qcan.adamsbridgestage.com/fileStorageService",
  invoiceRecordMailApiUrl: "http://localhost:22004/invoiceRecordsService/mailRecordsService/api/mailRead",
  recategoryid:"66b5ba7c996870547c64cdee",
  opportunityExecutedId : "68c40e9cc4a5062893076fcb",
  enableSingup: true,
    htmlPdf:"https://pdfapi.adamsbridgestage.com/pdfService/api/convertToPdf"

};
