export const environment = {
  production: true,
  ssoServiceUrl: "https://crmapi.adamsbridgestage.com/ssoService",
  // mongo_AuthServiceURL: "https://crmapi.adamsbridgestage.com/authService",
  mongo_AuthServiceURL: "https://loginapi.adamsbridgestage.com/authService",
  mongo_AuthServiceURL_commonAuth: "https://loginapi.adamsbridgestage.com/authService",

  mongo_FormServiceURL: "https://crmapi.adamsbridgestage.com/formService",
  mongo_RealServServiceURL: "https://crmapi.adamsbridgestage.com/realServService",
  report_builder_apiUrl: "https://crmapi.adamsbridgestage.com/reportBuilderService",
  CRM_ApiUrl: "https://crmapi.adamsbridgestage.com/CRMService",
  CRM_Transition_ApiUrl: "http://localhost:5010/CRMTransitionService",
  assetPath: "./",
  Companyid: "1",
  body: { UserName: "ticket", Password: "ao" + "sta", LogOpt: "1" },
  Ticket_Image: "https://ticketstage.adamsbridgestage.com",
  jsonUrl: "./assets/static-messages/static_eng_message.json",
  cryptoKey: "ao" + "sta" + "$123",
  enableSSO: false,
  reportServiceCollectionId: "2",
  layoutSetting: {
    createnew: false,
    settings: true,
    role: true,
    company: true
  },
  themeSetting: {
    abg: true,
    lil: true,
    ims: false,
    cms: true,
    abgLight: true,
  },

  SharedFilePath: "https://adamsbridgenet.sharepoint.com",
  SharePointAppName: "DevABGPortal",
  SHAREPOINT_CLIENT_ID: "2c70b035-8486-40f5-ab3b-c8523aecc76c@cf7323e2-013d-40b8-82a5-53db19b19fac",
  SHAREPOINT_SECRET: "2O5mj" + "FuMOcC" + "9oOEFS" + "0osqgU" + "7AaJG9" + "nqTexOo" + "vnUhxqg=",
  SHAREPOINT_RESOURCE: "00000003-0000-0ff1-ce00-000000000000/adamsbridgenet.sharepoint.com@cf7323e2-013d-40b8-82a5-53db19b19fac",
  SHAREPOINT_RESTCLIENT: "https://accounts.accesscontrol.windows.net/cf7323e2-013d-40b8-82a5-53db19b19fac/tokens/OAuth/2/",
  DOCUBEE_API_KEY: "ba7d1" + "3db-d1c7" + "-457d-8af0" + "-a995277" + "d43ac",
  DOCUBEE_API_URL: "https://app.ontask.io/api/v2/signatures",
  DOCUBEE_API_UPLOAD_URI: "https://app.ontask.io/api/v2/documents",
  DOCUBEE_API_SETFIELDS_URI: "https://docubee.app/api/v2/documents/",
  DOCUBEE_API_GET_SIGN_STATUS: "https://docubee.app/api/v2/signatures/",
  projectName: "crm",
  title:'CRM',
  ACCESS_KEY: "abg_fs_vB" + "abgohfGf" + "GnJfg3wW" + "hpXghR9Z" + "FoDr4JmJ" + "I10ZxuCv" + "E24fn2ku" + "f2UlRcUK" + "ks1FwLz8" + "mvt0BTTW" + "Z5OtF5NO" + "GqrPgIpc" + "eIZ27w7e" + "QQ9BqTKA" + "Qu9b52zR" + "sYQEAsb",
  recaptchaV3SiteKey: "6LfEVZYqAAAAAJb95Ytd0ldkpdGOp6VmWcxGQ0KY",
  recaptchaV2SiteKey: "6LcdcpgqAAAAADyhuuxCJhBhVjDsoFvvqjpZX7qq",
  recaptchaV2URL: "https://www.google.com/recaptcha/api.js",
  gtagURL: "https://www.googletagmanager.com/gtag/js?id=G-N9D1FB4L52",
  gtagKey: "G-N9D1FB4L52",
  recaptchaSiteKeyWithURL: "https://www.google.com/recaptcha/enterprise.js?render=6LfEVZYqAAAAAJb95Ytd0ldkpdGOp6VmWcxGQ0KY",
  scriptFile: 'script[src^="https://www.google.com/recaptcha/enterprise.js"]',
  ipAddressUrl: "https://ipapi.co/json/?key=" + "fnqdj6" + "xwio1A" + "vjrfHA" + "QHT59k" + "XLNIt9" + "U9BqOz" + "rGJsEn" + "Bisgtv" + "HR",
  AdminAccess: '67d92e105425c6d074a24df0',
  socketUrl: "https://loginapi.adamsbridgestage.com",
  mongo_common_AuthServiceURL: "https://crmapi.adamsbridgestage.com/authService",
  standAloneApp: false,
  crmProductsUrl: `https://crmapi.adamsbridgestage.com/CRMService`,
  status_prospect: "68188a07340c99536669d57e",
  status_contracting: "66b5dca9996870547c64d163",
  status_active: "66b5dce5996870547c64d173",
  status_inactive: "66b5dcf0996870547c64d17b",
  status_transition: "681996c4561f8c799500044f",
  status_DocumentEnd: "6837f0419d2a92b0a7a3e7af",
  ticketingArticleUrl: `https://ticketapi.adamsbridgestage.com/ticketingService/ticketingService`,
  ticketkingAppUrl: `https://ticket.adamsbridgestage.com/#/ticket`,
  crm_socket: "https://crmapi.adamsbridgestage.com",
  audit_logUrl: "https://crm.adamsbridgestage.com/CRMService/fileTransaction",
  fileStorageApiUrl: "https://ticketapi.adamsbridgestage.com/fileStorageService/fileStorageService",
  invoiceRecordMailApiUrl:
    "https://abstractapi.adamsbridgestage.com/invoiceRecordsService/mailRecordsService/api/mailRead",
  recategoryid: "66b5ba7c996870547c64cdee",
  opportunityExecutedId : "68d0d2548167dee41fbd7d5e",
  enableSingup: true,
    htmlPdf:"https://pdfapi.adamsbridgestage.com/pdfService/api/convertToPdf"

};
