export const environment = {
  production: true,
  ssoServiceUrl: "https://customerapi.adamsbridge.com/ssoService",
  mongo_AuthServiceURL: "https://loginapi.adamsbridge.com/authService",
  mongo_FormServiceURL: "https://customerapi.adamsbridge.com/formService",
  mongo_RealServServiceURL: "https://customerapi.adamsbridge.com/realServService",
  report_builder_apiUrl: "https://customerapi.adamsbridge.com/reportBuilderService",
  CRM_ApiUrl: "https://customerapi.adamsbridge.com/CRMService",
  CRM_Transition_ApiUrl: "http://localhost:5010/CRMTransitionService",
  assetPath: "./",
  Companyid: "1",
  body: { UserName: "ticket", Password: "ao" + "sta", LogOpt: "1" },
  Ticket_Image: "https://ticketstage.adamsbridgestage.com",
  jsonUrl: "./assets/static-messages/static_eng_message.json",
  cryptoKey: "ao" + "sta" + "$123",
  enableSSO: false,
  reportServiceCollectionId: "2",
  layoutSetting: {
    createnew: false,
    settings: true,
    role: true,
    company: true
  },
  themeSetting: {
    abg: true,
    lil: true,
    ims: true,
    cms: true,
    abgLight: true,
  },
  SharedFilePath: "https://adamsbridgenet.sharepoint.com",
  SharePointAppName: "CRMPortal",
  SHAREPOINT_CLIENT_ID: "25281897-d9ac-4b65-9f5f-a5f74071a0fe@cf7323e2-013d-40b8-82a5-53db19b19fac",
  SHAREPOINT_SECRET: "qsT/M" + "Hl0x0" + "Rdns2L" + "vuL0Tw" + "N95joY" + "UylJMcF" + "rTNdNezA=",
  SHAREPOINT_RESOURCE: "00000003-0000-0ff1-ce00-000000000000/adamsbridgenet.sharepoint.com@cf7323e2-013d-40b8-82a5-53db19b19fac",
  SHAREPOINT_RESTCLIENT: "https://accounts.accesscontrol.windows.net/cf7323e2-013d-40b8-82a5-53db19b19fac/tokens/OAuth/2/",
  DOCUBEE_API_KEY: "ba7d1" + "3db-d1c7" + "-457d-8af0" + "-a995277" + "d43ac",
  DOCUBEE_API_URL: "https://app.ontask.io/api/v2/signatures",
  DOCUBEE_API_UPLOAD_URI: "https://app.ontask.io/api/v2/documents",
  DOCUBEE_API_SETFIELDS_URI: "https://docubee.app/api/v2/documents/",
  DOCUBEE_API_GET_SIGN_STATUS: "https://docubee.app/api/v2/signatures/",
  projectName: "crm",
  ACCESS_KEY: "abg_fs_vB" + "abgohfGf" + "GnJfg3wW" + "hpXghR9Z" + "FoDr4JmJ" + "I10ZxuCv" + "E24fn2ku" + "f2UlRcUK" + "ks1FwLz8" + "mvt0BTTW" + "Z5OtF5NO" + "GqrPgIpc" + "eIZ27w7e" + "QQ9BqTKA" + "Qu9b52zR" + "sYQEAsb",
  recaptchaV3SiteKey: "6LffVJYqAAAAAK4N_I1lNFClv8027f0w4cNQ32s-",
  recaptchaV2SiteKey: "6LcdcpgqAAAAADyhuuxCJhBhVjDsoFvvqjpZX7qq",
  recaptchaV2URL: "https://www.google.com/recaptcha/api.js",
  gtagURL: "https://www.googletagmanager.com/gtag/js?id=G-QNP6L3C8YJ",
  gtagKey: "G-QNP6L3C8YJ",
  recaptchaSiteKeyWithURL: "https://www.google.com/recaptcha/enterprise.js?render=6LffVJYqAAAAAK4N_I1lNFClv8027f0w4cNQ32s-",
  scriptFile: `script[src^="https://www.google.com/recaptcha/enterprise.js"]`,
  ipAddressUrl: "https://ipapi.co/json/?key=" + "fnqdj6" + "xwio1A" + "vjrfHA" + "QHT59k" + "XLNIt9" + "U9BqOz" + "rGJsEn" + "Bisgtv" + "HR",
  AdminAccess: '680e01b47882d919b953e8bf',
  socketUrl: "https://loginapi.adamsbridge.com",
  mongo_common_AuthServiceURL: "https://customerapi.adamsbridge.com/authService",
  standAloneApp: false,
  crmProductsUrl: `https://customerapi.adamsbridge.com/CRMService`,
  mongo_AuthServiceURL_commonAuth: "https://loginapi.adamsbridge.com/authService",
  status_prospect: "6818a8461adf914a7742d5b2",
  status_contracting: "66b5dca9996870547c64d163",
  status_active: "66b5dce5996870547c64d173",
  status_inactive: "66b5dcf0996870547c64d17b",
  status_transition: "6818caeb11478cddc16602ca",
  status_DocumentEnd: "682c879bc39be92aecdc112e",
  ticketingArticleUrl: `https://ticketapi.adamsbridge.com`,
  ticketkingAppUrl: `https://ticket.adamsbridge.com/#/ticket`,
  crm_socket: "https://customerapi.adamsbridge.com",
  crm_transition_socket: "https://customerapi.adamsbridge.com",
  fileStorageApiUrl: "https://ticketapi.adamsbridge/fileStorageService",
  invoiceRecordMailApiUrl: "https://abstractapi.adamsbridge.com/invoiceRecordsService/mailRecordsService/api/mailRead",
  recategoryid: "66b5ba7c996870547c64cdee",
  opportunityExecutedId: "68c40e9cc4a5062893076fcb",
  enableSingup: true,
  htmlPdf: "https://pdfapi.adamsbridgestage.com/pdfService/api/convertToPdf",
  audit_logUrl: "https://customerapi.adamsbridge.com/CRMService/fileTransaction",
 title:'CRM',

};
